"""Direct C library interface tests via CFFI.

Includes:
- Basic initGraph / labelling smoke tests (E-n22-k4)
- Pricing regression tests with a fixed 6-node synthetic graph
- Determinism test
- Stress invariant tests (capacity, depot, elementarity)
"""

import json
import math
import os
import time

import pytest

from src.labelling import LabellingLib

# -----------------------------------------------------------------------
# Load regression data from JSON (single source of truth)
# Generated by: python tests/capture_regression_values.py
# -----------------------------------------------------------------------

_REGRESSION_FILE = os.path.join(os.path.dirname(__file__), "regression_values.json")
with open(_REGRESSION_FILE) as _f:
    REGRESSION = json.load(_f)

_graph = REGRESSION["graph"]
SYNTH_NUM_NODES = _graph["num_nodes"]
SYNTH_DEMANDS = _graph["demands"]
SYNTH_CAPACITY = _graph["capacity"]
SYNTH_EDGES = _graph["edges"]
SYNTH_DUALS = _graph["duals"]
SYNTH_FLAT_EDGES = [
    float(SYNTH_EDGES[i][j])
    for i in range(SYNTH_NUM_NODES)
    for j in range(SYNTH_NUM_NODES)
]
SYNTH_MAX_PATH_LEN = math.ceil(2 * SYNTH_CAPACITY / min(SYNTH_DEMANDS[1:])) + 2


@pytest.fixture()
def synth_cffi():
    """Init the synthetic 6-node graph in the C library, return LabellingLib."""
    lib = LabellingLib()
    lib.init_graph(SYNTH_NUM_NODES, SYNTH_DEMANDS, SYNTH_FLAT_EDGES,
                   SYNTH_CAPACITY, SYNTH_MAX_PATH_LEN, [0])
    return lib


def _run_synth_labelling(lib, elementary=False, cyc2=False, max_vars=20):
    """Run labelling on the synthetic graph with SYNTH_DUALS. Returns (num_paths, paths)."""
    result = lib.run_labelling(
        SYNTH_DUALS, SYNTH_MAX_PATH_LEN, max_vars,
        elementary=elementary, cyc2=cyc2,
    )
    return result.num_paths, result.paths


def _reduced_cost(path):
    """Compute reduced cost for a path on the synthetic graph."""
    edge_cost = sum(SYNTH_EDGES[path[k]][path[k + 1]] for k in range(len(path) - 1))
    dual_sum = sum(SYNTH_DUALS[node - 1] for node in path[1:-1])
    return edge_cost - dual_sum - SYNTH_DUALS[-1]


def _load(path):
    return sum(SYNTH_DEMANDS[node] for node in path[1:-1])


# -----------------------------------------------------------------------
# Basic smoke tests (E-n22-k4)
# -----------------------------------------------------------------------

class TestInitGraph:

    def test_init_graph_does_not_crash(self, init_e_n22_k4_graph):
        """initGraph should complete without error."""
        lib, G, max_path_len = init_e_n22_k4_graph
        assert G.number_of_nodes() == 22


class TestLabelling:

    def test_labelling_returns_paths(self, init_e_n22_k4_graph):
        """Call labelling() with uniform duals and verify paths come back."""
        lib, G, max_path_len = init_e_n22_k4_graph
        num_nodes = G.number_of_nodes()
        dual = [100.0] * (num_nodes - 1) + [0.0]
        max_vars = 10

        result = lib.run_labelling(dual, max_path_len, max_vars, ng_param=8)

        assert result.num_paths > 0
        path = result.paths[0]
        assert path[0] == 0, "Path should start at depot (0)"
        assert path[-1] == 0, "Path should end at depot (0)"

    def test_labelling_respects_capacity(self, init_e_n22_k4_graph):
        """Verify returned paths don't exceed vehicle capacity."""
        lib, G, max_path_len = init_e_n22_k4_graph
        num_nodes = G.number_of_nodes()
        capacity = G.graph["capacity"]
        dual = [100.0] * (num_nodes - 1) + [0.0]
        max_vars = 10

        result = lib.run_labelling(dual, max_path_len, max_vars, ng_param=8)

        for idx, path in enumerate(result.paths):
            load = sum(G.nodes[node]["demand"] for node in path[1:-1])
            assert load <= capacity, (
                f"Path {idx} has load {load} > capacity {capacity}"
            )

    def test_labelling_spprc_mode(self, init_e_n22_k4_graph):
        """Call labelling in SPPRC mode (ngParam=0, no elementary)."""
        lib, G, max_path_len = init_e_n22_k4_graph
        num_nodes = G.number_of_nodes()
        dual = [100.0] * (num_nodes - 1) + [0.0]
        max_vars = 10

        result = lib.run_labelling(dual, max_path_len, max_vars)

        assert result.num_paths > 0

    def test_labelling_cyc2_mode(self, init_e_n22_k4_graph):
        """Call labelling in cyc2 mode."""
        lib, G, max_path_len = init_e_n22_k4_graph
        num_nodes = G.number_of_nodes()
        dual = [100.0] * (num_nodes - 1) + [0.0]
        max_vars = 10

        result = lib.run_labelling(dual, max_path_len, max_vars, cyc2=True)

        assert result.num_paths > 0


# -----------------------------------------------------------------------
# Pricing regression tests (synthetic 6-node graph, fixed duals)
#
# Expected values loaded from tests/regression_values.json
# Regenerate with: python tests/capture_regression_values.py
# -----------------------------------------------------------------------

class TestPricingRegression:

    def test_spprc_no_truncation(self, synth_cffi):
        """Ensure max_vars is high enough that no paths are truncated."""
        max_vars = 20
        num_paths, paths = _run_synth_labelling(synth_cffi, elementary=False, max_vars=max_vars)
        assert num_paths < max_vars, (
            f"num_paths ({num_paths}) >= max_vars ({max_vars}), results may be truncated"
        )

    def test_elementary_no_truncation(self, synth_cffi):
        """Ensure max_vars is high enough that no elementary paths are truncated."""
        max_vars = 20
        num_paths, paths = _run_synth_labelling(synth_cffi, elementary=True, max_vars=max_vars)
        assert num_paths < max_vars, (
            f"num_paths ({num_paths}) >= max_vars ({max_vars}), results may be truncated"
        )

    def test_spprc_num_paths(self, synth_cffi):
        num_paths, paths = _run_synth_labelling(synth_cffi, elementary=False)
        assert num_paths == REGRESSION["spprc"]["num_paths"]

    def test_spprc_best_reduced_cost(self, synth_cffi):
        num_paths, paths = _run_synth_labelling(synth_cffi, elementary=False)
        best_rc = min(_reduced_cost(p) for p in paths)
        assert best_rc == pytest.approx(REGRESSION["spprc"]["best_reduced_cost"])

    def test_spprc_sorted_reduced_costs(self, synth_cffi):
        num_paths, paths = _run_synth_labelling(synth_cffi, elementary=False)
        actual = sorted(_reduced_cost(p) for p in paths)
        assert actual == pytest.approx(REGRESSION["spprc"]["sorted_reduced_costs"])

    def test_elementary_num_paths(self, synth_cffi):
        num_paths, paths = _run_synth_labelling(synth_cffi, elementary=True)
        assert num_paths == REGRESSION["elementary"]["num_paths"]

    def test_elementary_best_reduced_cost(self, synth_cffi):
        num_paths, paths = _run_synth_labelling(synth_cffi, elementary=True)
        best_rc = min(_reduced_cost(p) for p in paths)
        assert best_rc == pytest.approx(REGRESSION["elementary"]["best_reduced_cost"])

    def test_elementary_sorted_reduced_costs(self, synth_cffi):
        num_paths, paths = _run_synth_labelling(synth_cffi, elementary=True)
        actual = sorted(_reduced_cost(p) for p in paths)
        assert actual == pytest.approx(REGRESSION["elementary"]["sorted_reduced_costs"])


# Determinism test

class TestDeterminism:

    def test_deterministic_spprc(self, synth_cffi):
        """Running SPPRC twice with identical inputs must produce identical output."""
        _, paths1 = _run_synth_labelling(synth_cffi, elementary=False)
        _, paths2 = _run_synth_labelling(synth_cffi, elementary=False)
        assert sorted(paths1) == sorted(paths2)

    def test_deterministic_elementary(self, synth_cffi):
        """Running elementary twice with identical inputs must produce identical output."""
        _, paths1 = _run_synth_labelling(synth_cffi, elementary=True)
        _, paths2 = _run_synth_labelling(synth_cffi, elementary=True)
        assert sorted(paths1) == sorted(paths2)


# Stress invariant tests

class TestInvariants:

    def test_all_paths_start_and_end_at_depot(self, synth_cffi):
        """Every returned path must start and end at depot (0)."""
        for elementary in [False, True]:
            _, paths = _run_synth_labelling(synth_cffi, elementary=elementary)
            for path in paths:
                assert path[0] == 0, f"Path {path} does not start at depot"
                assert path[-1] == 0, f"Path {path} does not end at depot"

    def test_all_paths_respect_capacity(self, synth_cffi):
        """Every returned path must have load <= capacity."""
        for elementary in [False, True]:
            _, paths = _run_synth_labelling(synth_cffi, elementary=elementary)
            for path in paths:
                load = _load(path)
                assert load <= SYNTH_CAPACITY, (
                    f"Path {path} has load {load} > capacity {SYNTH_CAPACITY}"
                )

    def test_elementary_no_duplicate_nodes(self, synth_cffi):
        """In elementary mode, no customer node should appear twice in a path."""
        _, paths = _run_synth_labelling(synth_cffi, elementary=True)
        for path in paths:
            customers = path[1:-1]
            assert len(customers) == len(set(customers)), (
                f"Elementary path {path} has duplicate customers"
            )

    def test_spprc_allows_non_elementary(self, synth_cffi):
        """SPPRC should produce at least one non-elementary path on this graph."""
        _, paths = _run_synth_labelling(synth_cffi, elementary=False)
        has_dupes = any(
            len(p[1:-1]) != len(set(p[1:-1])) for p in paths
        )
        assert has_dupes, "SPPRC should allow non-elementary paths on this graph"

    def test_all_reduced_costs_negative(self, synth_cffi):
        """Every returned path must have negative reduced cost."""
        for elementary in [False, True]:
            _, paths = _run_synth_labelling(synth_cffi, elementary=elementary)
            for path in paths:
                rc = _reduced_cost(path)
                assert rc < -1e-6, (
                    f"Path {path} has non-negative reduced cost {rc}"
                )


# -----------------------------------------------------------------------
# Time limit test
# -----------------------------------------------------------------------

class TestPerformance:

    def test_e_n22_k4_under_10s(self, init_e_n22_k4_graph):
        """E-n22-k4 labelling with ng8 should complete well under 10 seconds."""
        lib, G, max_path_len = init_e_n22_k4_graph
        num_nodes = G.number_of_nodes()
        dual = [100.0] * (num_nodes - 1) + [0.0]
        max_vars = 10

        t0 = time.time()
        lib.run_labelling(dual, max_path_len, max_vars, ng_param=8)
        elapsed = time.time() - t0

        assert elapsed < 10.0, f"Labelling took {elapsed:.1f}s, expected < 10s"

    def test_synth_spprc_under_1s(self, synth_cffi):
        """Synthetic 6-node SPPRC should complete in well under 1 second."""
        t0 = time.time()
        _run_synth_labelling(synth_cffi, elementary=False)
        elapsed = time.time() - t0
        assert elapsed < 1.0, f"Synthetic SPPRC took {elapsed:.1f}s, expected < 1s"
